### PR TITLE
Remove unnecessary branch retrieval loop

### PR DESCRIPTION
**Pull request by justusbunsi**
The Gitea bug https://github.com/go-gitea/gitea/issues/2088 that was mentioned in the code was fixed years ago. I built the plugin and tested it. It worked but I am not 100% sure in which exact situation this code block was executed.

### CODE REVIEW

**Comment by viceice** [comment]
You should open this PR to upstream. This is only a mirror with some fixes missing upstream. 🤗

**Comment by justusbunsi** [comment]
Thanks for your reply. I know this is just a fork and of course I will create a PR for this in upstream. But I am afraid it won't be taken care of soon (regarding the past few months).
Right now I use the releases of this fork as Jenkins Plugin since it handles lookup for all branches/tags and thought I could contribute to something I use on a daily basis. 😉

**Review by viceice — APPROVED** [review]
So this changes are working fine for you?

**Comment by justusbunsi** [comment]
Yep, it does.

I had a closer look at where this is actually been called. Turns out, it's called during a build as one of the first actions to retrieve the actual revision. In my repositories I always use branch patterns like `<bug|feature|task>/<summarized-content>`. This is exactly the mentioned case in which all branches are fetched to get the only one that is needed.
In my environment this took about 20 seconds, speaking of repositories with more than 400 branches. In Gitea web logs I see that all those branches are retrieved page per page.

With this fix, this part of the build takes only 200ms. 🤗

**Comment by viceice** [comment]
Should be included in next release.

**Comment by justusbunsi** [comment]
Thanks. I'll create a PR for the upstream as well. 😃

**Pull request merged**
